In [2]:
import pandas as pd
from datetime import datetime
from datetime import date
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('igdb_dataset.csv', low_memory = False)
df

,id,name,platforms,first_release_date,category,genres,themes,player_perspectives,rating,rating_count,similar_games,total_rating,total_rating_count,url,aggregated_rating,aggregated_rating_count
0,70.0,"""TerraNova:StrikeForceCentauri""",13,8.259840e+08,0.0,"5,13,15","1,18",1,70.0,2.0,"13200,16806,17130,24620,25311,34823,55038,6828...",81.000000,3.0,"""https://www.igdb.com/games/terra-nova-strike-...",92.0,1.0
1,40104.0,"""DogouSouken""",52,5.364576e+08,0.0,5,NaN,NaN,NaN,NaN,"12364,27270,43367,103281,103292,103298,103301,...",NaN,NaN,"""https://www.igdb.com/games/dogou-souken""",NaN,NaN
2,51663.0,"""TheFiremen2:Pete&Danny""",NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"""https://www.igdb.com/games/the-firemen-2-pete...",NaN,NaN
3,86911.0,"""Baccarat-BestCasinoBettingGame""",14,1.381968e+09,0.0,NaN,NaN,NaN,NaN,NaN,"59426,75894,86811,86969,86981,86987,87087,8909...",NaN,NaN,"""https://www.igdb.com/games/baccarat-best-casi...",NaN,NaN
4,68841.0,"""Captivus""",6,1.506989e+09,0.0,"15,16",18,NaN,NaN,NaN,"11666,13200,13660,16806,17130,24620,32510,3482...",NaN,NaN,"""https://www.igdb.com/games/captivus""",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135058,29532.0,"""TheMoonstoneEquation""",6,1.530317e+09,0.0,"8,31,32",NaN,4,70.0,0.0,"28070,28277,75948,81275,89597,106992,108778,11...",70.000000,0.0,"""https://www.igdb.com/games/the-moonstone-equa...",NaN,NaN
135059,89201.0,"""MagicMermaid""",39,1.496102e+09,0.0,12,NaN,NaN,90.0,0.0,"25636,35737,49414,51213,56036,94981,99118,1112...",90.000000,0.0,"""https://www.igdb.com/games/magic-mermaid""",NaN,NaN
135060,46274.0,"""JoeMontanaII:SportstalkFootball""",29,6.730560e+08,0.0,14,NaN,NaN,NaN,NaN,"14733,109606,116343,116349,116350,116351,11635...",NaN,NaN,"""https://www.igdb.com/games/joe-montana-ii-spo...",NaN,NaN
135061,18879.0,"""Horde:TheNorthernWind""",6,9.415872e+08,0.0,"11,32","17,22,38",3,82.3178111078051,6.0,"18623,19164,78550,81249,96217,102163,113360,11...",82.317811,6.0,"""https://www.igdb.com/games/horde-the-northern...",NaN,NaN
135062,96616.0,"""TimeTenshiParadox:Episode2""",NaN,NaN,0.0,"13,31,32",NaN,NaN,50.0,0.0,"28277,37419,81275,81680,87975,105011,108778,10...",50.000000,0.0,"""https://www.igdb.com/games/time-tenshi-parado...",NaN,NaN

In [4]:
df['first_release_date'] = pd.to_datetime(df['first_release_date'], unit='s')

In [5]:
df

,id,name,platforms,first_release_date,category,genres,themes,player_perspectives,rating,rating_count,similar_games,total_rating,total_rating_count,url,aggregated_rating,aggregated_rating_count
0,70.0,"""TerraNova:StrikeForceCentauri""",13,1996-03-05,0.0,"5,13,15","1,18",1,70.0,2.0,"13200,16806,17130,24620,25311,34823,55038,6828...",81.000000,3.0,"""https://www.igdb.com/games/terra-nova-strike-...",92.0,1.0
1,40104.0,"""DogouSouken""",52,1987-01-01,0.0,5,NaN,NaN,NaN,NaN,"12364,27270,43367,103281,103292,103298,103301,...",NaN,NaN,"""https://www.igdb.com/games/dogou-souken""",NaN,NaN
2,51663.0,"""TheFiremen2:Pete&Danny""",NaN,NaT,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"""https://www.igdb.com/games/the-firemen-2-pete...",NaN,NaN
3,86911.0,"""Baccarat-BestCasinoBettingGame""",14,2013-10-17,0.0,NaN,NaN,NaN,NaN,NaN,"59426,75894,86811,86969,86981,86987,87087,8909...",NaN,NaN,"""https://www.igdb.com/games/baccarat-best-casi...",NaN,NaN
4,68841.0,"""Captivus""",6,2017-10-03,0.0,"15,16",18,NaN,NaN,NaN,"11666,13200,13660,16806,17130,24620,32510,3482...",NaN,NaN,"""https://www.igdb.com/games/captivus""",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135058,29532.0,"""TheMoonstoneEquation""",6,2018-06-30,0.0,"8,31,32",NaN,4,70.0,0.0,"28070,28277,75948,81275,89597,106992,108778,11...",70.000000,0.0,"""https://www.igdb.com/games/the-moonstone-equa...",NaN,NaN
135059,89201.0,"""MagicMermaid""",39,2017-05-30,0.0,12,NaN,NaN,90.0,0.0,"25636,35737,49414,51213,56036,94981,99118,1112...",90.000000,0.0,"""https://www.igdb.com/games/magic-mermaid""",NaN,NaN
135060,46274.0,"""JoeMontanaII:SportstalkFootball""",29,1991-05-01,0.0,14,NaN,NaN,NaN,NaN,"14733,109606,116343,116349,116350,116351,11635...",NaN,NaN,"""https://www.igdb.com/games/joe-montana-ii-spo...",NaN,NaN
135061,18879.0,"""Horde:TheNorthernWind""",6,1999-11-03,0.0,"11,32","17,22,38",3,82.3178111078051,6.0,"18623,19164,78550,81249,96217,102163,113360,11...",82.317811,6.0,"""https://www.igdb.com/games/horde-the-northern...",NaN,NaN
135062,96616.0,"""TimeTenshiParadox:Episode2""",NaN,NaT,0.0,"13,31,32",NaN,NaN,50.0,0.0,"28277,37419,81275,81680,87975,105011,108778,10...",50.000000,0.0,"""https://www.igdb.com/games/time-tenshi-parado...",NaN,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135063 entries, 0 to 135062
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       135062 non-null  float64
 1   name                     135061 non-null  object
 2   platforms                75337 non-null   object
 3   first_release_date       73294 non-null   datetime64[ns]
 4   category                 135062 non-null  float64
 5   genres                   92472 non-null   object
 6   themes                   59622 non-null   object
 7   player_perspectives      36100 non-null   object
 8   rating                   31303 non-null   object
 9   rating_count             31300 non-null   float64
 10  similar_games            99347 non-null   object
 11  total_rating             31300 non-null   float64
 12  total_rating_count       31300 non-null   float64
 13  url                      135061 non-null  object
 14  aggregated_rating        13124 non-null   float64
 15  aggregated_rating_count  13124 non-null   float64
dtypes: datetime64[ns](1), float64(7), object(8)
memory usage: 16.5+ MB

In [7]:
df.head()

,id,name,platforms,first_release_date,category,genres,themes,player_perspectives,rating,rating_count,similar_games,total_rating,total_rating_count,url,aggregated_rating,aggregated_rating_count
0,70.0,"""TerraNova:StrikeForceCentauri""",13,1996-03-05,0.0,"5,13,15","1,18",1,70.0,2.0,"13200,16806,17130,24620,25311,34823,55038,6828...",81.0,3.0,"""https://www.igdb.com/games/terra-nova-strike-...",92.0,1.0
1,40104.0,"""DogouSouken""",52,1987-01-01,0.0,5,NaN,NaN,NaN,NaN,"12364,27270,43367,103281,103292,103298,103301,...",NaN,NaN,"""https://www.igdb.com/games/dogou-souken""",NaN,NaN
2,51663.0,"""TheFiremen2:Pete&Danny""",NaN,NaT,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"""https://www.igdb.com/games/the-firemen-2-pete...",NaN,NaN
3,86911.0,"""Baccarat-BestCasinoBettingGame""",14,2013-10-17,0.0,NaN,NaN,NaN,NaN,NaN,"59426,75894,86811,86969,86981,86987,87087,8909...",NaN,NaN,"""https://www.igdb.com/games/baccarat-best-casi...",NaN,NaN
4,68841.0,"""Captivus""",6,2017-10-03,0.0,"15,16",18,NaN,NaN,NaN,"11666,13200,13660,16806,17130,24620,32510,3482...",NaN,NaN,"""https://www.igdb.com/games/captivus""",NaN,NaN

In [8]:
df.describe()

,id,category,rating_count,total_rating,total_rating_count,aggregated_rating,aggregated_rating_count
count,135062.000000,135062.000000,31300.000000,31300.000000,31300.00000,13124.000000,13124.000000
mean,70664.254972,0.081777,13.901086,66.132921,15.26885,68.438922,3.680204
std,40694.453733,0.534446,75.022597,14.886746,76.43429,16.351182,4.136703
min,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,35540.250000,0.000000,0.000000,57.500000,0.00000,60.000000,1.000000
50%,70690.500000,0.000000,1.000000,70.000000,1.00000,70.000000,2.000000
75%,105830.750000,0.000000,5.000000,77.500000,6.00000,80.000000,4.000000
max,141114.000000,7.000000,2783.000000,100.000000,2817.00000,100.000000,60.000000

In [9]:
df.tail()

,id,name,platforms,first_release_date,category,genres,themes,player_perspectives,rating,rating_count,similar_games,total_rating,total_rating_count,url,aggregated_rating,aggregated_rating_count
135058,29532.0,"""TheMoonstoneEquation""",6,2018-06-30,0.0,"8,31,32",NaN,4,70.0,0.0,"28070,28277,75948,81275,89597,106992,108778,11...",70.000000,0.0,"""https://www.igdb.com/games/the-moonstone-equa...",NaN,NaN
135059,89201.0,"""MagicMermaid""",39,2017-05-30,0.0,12,NaN,NaN,90.0,0.0,"25636,35737,49414,51213,56036,94981,99118,1112...",90.000000,0.0,"""https://www.igdb.com/games/magic-mermaid""",NaN,NaN
135060,46274.0,"""JoeMontanaII:SportstalkFootball""",29,1991-05-01,0.0,14,NaN,NaN,NaN,NaN,"14733,109606,116343,116349,116350,116351,11635...",NaN,NaN,"""https://www.igdb.com/games/joe-montana-ii-spo...",NaN,NaN
135061,18879.0,"""Horde:TheNorthernWind""",6,1999-11-03,0.0,"11,32","17,22,38",3,82.3178111078051,6.0,"18623,19164,78550,81249,96217,102163,113360,11...",82.317811,6.0,"""https://www.igdb.com/games/horde-the-northern...",NaN,NaN
135062,96616.0,"""TimeTenshiParadox:Episode2""",NaN,NaT,0.0,"13,31,32",NaN,NaN,50.0,0.0,"28277,37419,81275,81680,87975,105011,108778,10...",50.000000,0.0,"""https://www.igdb.com/games/time-tenshi-parado...",NaN,NaN

In [10]:
df.describe()

,id,category,rating_count,total_rating,total_rating_count,aggregated_rating,aggregated_rating_count
count,135062.000000,135062.000000,31300.000000,31300.000000,31300.00000,13124.000000,13124.000000
mean,70664.254972,0.081777,13.901086,66.132921,15.26885,68.438922,3.680204
std,40694.453733,0.534446,75.022597,14.886746,76.43429,16.351182,4.136703
min,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,35540.250000,0.000000,0.000000,57.500000,0.00000,60.000000,1.000000
50%,70690.500000,0.000000,1.000000,70.000000,1.00000,70.000000,2.000000
75%,105830.750000,0.000000,5.000000,77.500000,6.00000,80.000000,4.000000
max,141114.000000,7.000000,2783.000000,100.000000,2817.00000,100.000000,60.000000

In [11]:
df.shape

(135063, 16)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135063 entries, 0 to 135062
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       135062 non-null  float64
 1   name                     135061 non-null  object
 2   platforms                75337 non-null   object
 3   first_release_date       73294 non-null   datetime64[ns]
 4   category                 135062 non-null  float64
 5   genres                   92472 non-null   object
 6   themes                   59622 non-null   object
 7   player_perspectives      36100 non-null   object
 8   rating                   31303 non-null   object
 9   rating_count             31300 non-null   float64
 10  similar_games            99347 non-null   object
 11  total_rating             31300 non-null   float64
 12  total_rating_count       31300 non-null   float64
 13  url                      135061 non-null  object
 14  aggregated_rating        13124 non-null   float64
 15  aggregated_rating_count  13124 non-null   float64
dtypes: datetime64[ns](1), float64(7), object(8)
memory usage: 16.5+ MB

In [13]:
df.isna().sum()

id                              1
name                            2
platforms                   59726
first_release_date          61769
category                        1
genres                      42591
themes                      75441
player_perspectives         98963
rating                     103760
rating_count               103763
similar_games               35716
total_rating               103763
total_rating_count         103763
url                             2
aggregated_rating          121939
aggregated_rating_count    121939
dtype: int64

# 1)What’s the first game ever released and when (not created)?

In [14]:
df.dropna()

,id,name,platforms,first_release_date,category,genres,themes,player_perspectives,rating,rating_count,similar_games,total_rating,total_rating_count,url,aggregated_rating,aggregated_rating_count
0,70.0,"""TerraNova:StrikeForceCentauri""",13,1996-03-05,0.0,"5,13,15","1,18",1,70.0,2.0,"13200,16806,17130,24620,25311,34823,55038,6828...",81.000000,3.0,"""https://www.igdb.com/games/terra-nova-strike-...",92.000000,1.0
41,14543.0,"""BioShock2:Minerva'sDen""","6,9,12",2010-08-31,1.0,"5,31","1,18",1,85.3701565860567,32.0,"55038,103276,103281,103292,103301,103329,10504...",83.185078,33.0,"""https://www.igdb.com/games/bioshock-2-minerva...",81.000000,1.0
124,76770.0,"""BridgeConstructorPortal""","3,6,14,34,39,48,49,130",2017-12-20,0.0,"9,13,15",18,4,71.2055474224599,19.0,"8773,11666,13200,17130,24620,25311,34823,36258...",75.727774,23.0,"""https://www.igdb.com/games/bridge-constructor...",80.250000,4.0
326,9637.0,"""OrcsMustDie!Unchained""","6,45,48",2017-03-19,0.0,"11,15,24,32","1,17",2,75.0901995625662,11.0,"2365,3222,5652,7027,9789,9834,9938,14394,19404",78.795100,13.0,"""https://www.igdb.com/games/orcs-must-die-unch...",82.500000,2.0
386,2129.0,"""MarkoftheNinja""","3,6,12,14",2012-09-07,0.0,"8,31,32","1,23",4,84.77759792635361,215.0,"3222,7213,11646,18182,19150,26226,26855,55190,...",88.103085,222.0,"""https://www.igdb.com/games/mark-of-the-ninja""",91.428571,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134889,80.0,"""TheWitcher""","6,14",2007-10-26,0.0,12,"1,17","2,3",83.0377583804557,442.0,"6,76,472,478,660,1887,1942,3025,9938",85.518879,446.0,"""https://www.igdb.com/games/the-witcher""",88.000000,4.0
134893,521.0,"""Fable""",11,2004-09-14,0.0,"12,31","1,17,22,33",2,86.5077929970646,164.0,"6,80,472,533,694,832,1026,1029,9927",88.253896,167.0,"""https://www.igdb.com/games/fable""",90.000000,3.0
134898,17583.0,"""SpellForce3""",6,2017-12-07,0.0,"11,12,15","1,17",3,38.9050765553989,13.0,"19404,22387,23733,27092,28168,36198,54775,5509...",56.452538,24.0,"""https://www.igdb.com/games/spellforce-3""",74.000000,11.0
134899,12527.0,"""Yakuza6:TheSongofLife""",48,2016-12-08,0.0,"14,25,31","1,38",2,84.94280278784339,16.0,"10776,11397,12595,12736,25300,26574,28309,3024...",83.794931,35.0,"""https://www.igdb.com/games/yakuza-6-the-song-...",82.647059,19.0
134926,25741.0,"""AshesoftheSingularity:Escalation""",6,2016-11-10,4.0,"11,12,13,15,32","18,39",3,78.0952380952381,5.0,"8773,9789,11666,13200,17130,25311,55029,78550,...",81.797619,7.0,"""https://www.igdb.com/games/ashes-of-the-singu...",85.500000,2.0

In [15]:
df.sort_values('first_release_date', ascending = True).head()

,id,name,platforms,first_release_date,category,genres,themes,player_perspectives,rating,rating_count,similar_games,total_rating,total_rating_count,url,aggregated_rating,aggregated_rating_count
30947,11321.0,"""CathodeRayTubeAmusementDevice""",100,1947-12-31,0.0,2,39,NaN,NaN,NaN,"236,9760,25222,27725,34024,55029,106805,112078...",NaN,NaN,"""https://www.igdb.com/games/cathode-ray-tube-a...",NaN,NaN
19539,11322.0,"""Nim""",101,1951-12-31,0.0,"15,30",34,NaN,NaN,NaN,"36258,51577,53189,65827,79134,102420,111150,11...",NaN,NaN,"""https://www.igdb.com/games/nim""",NaN,NaN
65608,11323.0,"""OXO""",102,1952-12-31,0.0,"9,15",34,NaN,NaN,NaN,"17613,19404,36346,36553,55036,55590,60044,7759...",NaN,NaN,"""https://www.igdb.com/games/oxo""",NaN,NaN
133339,6763.0,"""TennisforTwo""",85,1958-10-18,0.0,"14,33",1,4,85.0,4.0,"1333,15851,22799,72812,87728,115278,118871,120...",85.0,4.0,"""https://www.igdb.com/games/tennis-for-two""",NaN,NaN
65083,11301.0,"""Spacewar!""",95,1962-04-30,0.0,"5,13,30","1,18",3,NaN,NaN,"3239,17130,25311,26227,55038,57187,68286,68287...",NaN,NaN,"""https://www.igdb.com/games/spacewar""",NaN,NaN

In [16]:
df.sort_values('first_release_date', ascending = True).head(1)

,id,name,platforms,first_release_date,category,genres,themes,player_perspectives,rating,rating_count,similar_games,total_rating,total_rating_count,url,aggregated_rating,aggregated_rating_count
30947,11321.0,"""CathodeRayTubeAmusementDevice""",100,1947-12-31,0.0,2,39,NaN,NaN,NaN,"236,9760,25222,27725,34024,55029,106805,112078...",NaN,NaN,"""https://www.igdb.com/games/cathode-ray-tube-a...",NaN,NaN

In [17]:
df.sort_values('first_release_date', ascending = True).head(1)['name']

30947    "CathodeRayTubeAmusementDevice"
Name: name, dtype: object

In [18]:
df.sort_values('first_release_date', ascending = True).head(1)['first_release_date']

30947   1947-12-31
Name: first_release_date, dtype: datetime64[ns]

# 2)Which are the top 5 games of all time? (tip: many games score 100 rating and have a few reviews, other games score a bit lower but much higher reviews...)

In [19]:
df

,id,name,platforms,first_release_date,category,genres,themes,player_perspectives,rating,rating_count,similar_games,total_rating,total_rating_count,url,aggregated_rating,aggregated_rating_count
0,70.0,"""TerraNova:StrikeForceCentauri""",13,1996-03-05,0.0,"5,13,15","1,18",1,70.0,2.0,"13200,16806,17130,24620,25311,34823,55038,6828...",81.000000,3.0,"""https://www.igdb.com/games/terra-nova-strike-...",92.0,1.0
1,40104.0,"""DogouSouken""",52,1987-01-01,0.0,5,NaN,NaN,NaN,NaN,"12364,27270,43367,103281,103292,103298,103301,...",NaN,NaN,"""https://www.igdb.com/games/dogou-souken""",NaN,NaN
2,51663.0,"""TheFiremen2:Pete&Danny""",NaN,NaT,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"""https://www.igdb.com/games/the-firemen-2-pete...",NaN,NaN
3,86911.0,"""Baccarat-BestCasinoBettingGame""",14,2013-10-17,0.0,NaN,NaN,NaN,NaN,NaN,"59426,75894,86811,86969,86981,86987,87087,8909...",NaN,NaN,"""https://www.igdb.com/games/baccarat-best-casi...",NaN,NaN
4,68841.0,"""Captivus""",6,2017-10-03,0.0,"15,16",18,NaN,NaN,NaN,"11666,13200,13660,16806,17130,24620,32510,3482...",NaN,NaN,"""https://www.igdb.com/games/captivus""",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135058,29532.0,"""TheMoonstoneEquation""",6,2018-06-30,0.0,"8,31,32",NaN,4,70.0,0.0,"28070,28277,75948,81275,89597,106992,108778,11...",70.000000,0.0,"""https://www.igdb.com/games/the-moonstone-equa...",NaN,NaN
135059,89201.0,"""MagicMermaid""",39,2017-05-30,0.0,12,NaN,NaN,90.0,0.0,"25636,35737,49414,51213,56036,94981,99118,1112...",90.000000,0.0,"""https://www.igdb.com/games/magic-mermaid""",NaN,NaN
135060,46274.0,"""JoeMontanaII:SportstalkFootball""",29,1991-05-01,0.0,14,NaN,NaN,NaN,NaN,"14733,109606,116343,116349,116350,116351,11635...",NaN,NaN,"""https://www.igdb.com/games/joe-montana-ii-spo...",NaN,NaN
135061,18879.0,"""Horde:TheNorthernWind""",6,1999-11-03,0.0,"11,32","17,22,38",3,82.3178111078051,6.0,"18623,19164,78550,81249,96217,102163,113360,11...",82.317811,6.0,"""https://www.igdb.com/games/horde-the-northern...",NaN,NaN
135062,96616.0,"""TimeTenshiParadox:Episode2""",NaN,NaT,0.0,"13,31,32",NaN,NaN,50.0,0.0,"28277,37419,81275,81680,87975,105011,108778,10...",50.000000,0.0,"""https://www.igdb.com/games/time-tenshi-parado...",NaN,NaN

In [20]:
df = df.dropna()
df

,id,name,platforms,first_release_date,category,genres,themes,player_perspectives,rating,rating_count,similar_games,total_rating,total_rating_count,url,aggregated_rating,aggregated_rating_count
0,70.0,"""TerraNova:StrikeForceCentauri""",13,1996-03-05,0.0,"5,13,15","1,18",1,70.0,2.0,"13200,16806,17130,24620,25311,34823,55038,6828...",81.000000,3.0,"""https://www.igdb.com/games/terra-nova-strike-...",92.000000,1.0
41,14543.0,"""BioShock2:Minerva'sDen""","6,9,12",2010-08-31,1.0,"5,31","1,18",1,85.3701565860567,32.0,"55038,103276,103281,103292,103301,103329,10504...",83.185078,33.0,"""https://www.igdb.com/games/bioshock-2-minerva...",81.000000,1.0
124,76770.0,"""BridgeConstructorPortal""","3,6,14,34,39,48,49,130",2017-12-20,0.0,"9,13,15",18,4,71.2055474224599,19.0,"8773,11666,13200,17130,24620,25311,34823,36258...",75.727774,23.0,"""https://www.igdb.com/games/bridge-constructor...",80.250000,4.0
326,9637.0,"""OrcsMustDie!Unchained""","6,45,48",2017-03-19,0.0,"11,15,24,32","1,17",2,75.0901995625662,11.0,"2365,3222,5652,7027,9789,9834,9938,14394,19404",78.795100,13.0,"""https://www.igdb.com/games/orcs-must-die-unch...",82.500000,2.0
386,2129.0,"""MarkoftheNinja""","3,6,12,14",2012-09-07,0.0,"8,31,32","1,23",4,84.77759792635361,215.0,"3222,7213,11646,18182,19150,26226,26855,55190,...",88.103085,222.0,"""https://www.igdb.com/games/mark-of-the-ninja""",91.428571,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134889,80.0,"""TheWitcher""","6,14",2007-10-26,0.0,12,"1,17","2,3",83.0377583804557,442.0,"6,76,472,478,660,1887,1942,3025,9938",85.518879,446.0,"""https://www.igdb.com/games/the-witcher""",88.000000,4.0
134893,521.0,"""Fable""",11,2004-09-14,0.0,"12,31","1,17,22,33",2,86.5077929970646,164.0,"6,80,472,533,694,832,1026,1029,9927",88.253896,167.0,"""https://www.igdb.com/games/fable""",90.000000,3.0
134898,17583.0,"""SpellForce3""",6,2017-12-07,0.0,"11,12,15","1,17",3,38.9050765553989,13.0,"19404,22387,23733,27092,28168,36198,54775,5509...",56.452538,24.0,"""https://www.igdb.com/games/spellforce-3""",74.000000,11.0
134899,12527.0,"""Yakuza6:TheSongofLife""",48,2016-12-08,0.0,"14,25,31","1,38",2,84.94280278784339,16.0,"10776,11397,12595,12736,25300,26574,28309,3024...",83.794931,35.0,"""https://www.igdb.com/games/yakuza-6-the-song-...",82.647059,19.0
134926,25741.0,"""AshesoftheSingularity:Escalation""",6,2016-11-10,4.0,"11,12,13,15,32","18,39",3,78.0952380952381,5.0,"8773,9789,11666,13200,17130,25311,55029,78550,...",81.797619,7.0,"""https://www.igdb.com/games/ashes-of-the-singu...",85.500000,2.0

In [21]:
df[df['id']==5024.0]

,id,name,platforms,first_release_date,category,genres,themes,player_perspectives,rating,rating_count,similar_games,total_rating,total_rating_count,url,aggregated_rating,aggregated_rating_count
43040,5024.0,"""TheMunchables""",5,2009-05-27,0.0,8,"1,27",2,100.0,4.0,"19150,19164,24426,54775,55199,56033,76960,8091...",100.0,4.0,"""https://www.igdb.com/games/the-munchables""",100.0,4.0

In [22]:
df['rating']= pd.to_numeric(df['rating'], errors ='ignore')
df['rating']

C:\Users\klaud\AppData\Local\Temp\ipykernel_33732\4192123988.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating']= pd.to_numeric(df['rating'], errors ='ignore')

0         70.000000
41        85.370157
124       71.205547
326       75.090200
386       84.777598
            ...
134889    83.037758
134893    86.507793
134898    38.905077
134899    84.942803
134926    78.095238
Name: rating, Length: 7960, dtype: float64

In [39]:
df.groupby(['id','name']).sum().sort_values('weighted_score', ascending = False).head()

,,category,rating,rating_count,total_rating,total_rating_count,aggregated_rating,aggregated_rating_count,weighted_score,normalized_weighted_score
id,name,,,,,,,,,
1020.0,"""GrandTheftAutoV""",0.0,91.007003,2783.0,93.423502,2817.0,95.840000,34.0,253272.490450,100.000000
1942.0,"""TheWitcher3:WildHunt""",0.0,95.708657,2468.0,93.714329,2494.0,91.720000,26.0,236208.966262,93.262780
72.0,"""Portal2""",0.0,91.331534,2116.0,91.887989,2129.0,92.444444,13.0,193257.526516,76.304192
472.0,"""TheElderScrollsV:Skyrim""",0.0,87.714979,2184.0,91.913045,2196.0,96.111111,12.0,191569.514797,75.637711
1009.0,"""TheLastofUs""",0.0,94.494275,1835.0,93.016368,1851.0,91.538462,16.0,173396.994439,68.462625

In [24]:
#df['year'] = df['first_release_date'].dt.year
#df['month'] = df['first_release_date'].dt.month

In [25]:
#####df['rating'] = pd.to_numeric(df['rating'], error = 'ignore')

In [26]:
df[df['rating'].str.contains('.*[a-zA-Z].*') == True]

AttributeError: Can only use .str accessor with string values!

# 3)Do game ratings vary from year to year?

In [ ]:
df['year'] = pd.DatetimeIndex(df['first_release_date']).year
df['year']

In [ ]:
df = df.dropna()
df

In [ ]:
df['avg_total_rating'] = df['total_rating'].mean()
df['avg_total_rating']

In [ ]:
df.groupby('year').count()['avg_total_rating'].plot.bar(rot = 45, figsize=(15,5))
None

In [ ]:
df.groupby('year').count()['rating'].plot.bar(rot = 45, figsize=(15,5))
None

In [ ]:
df.groupby('year')['rating'].count().plot.bar(rot = 45, figsize=(15,5))
None

In [ ]:
result = df.groupby("year")["rating_count"].unique()
result.hist(by = df["year"])

# 4)In which year the most games were release

In [ ]:
df.groupby('year').count().sort_values(by = 'rating_count', ascending = False).head()# and without by = 'id' it still works

# 5)In the last 5 years, which month were released the most games per year, can you guess why?

In [ ]:
df['month'] = pd.DatetimeIndex(df['first_release_date']).month
df['month']

In [ ]:
df['year'] = pd.DatetimeIndex(df['first_release_date']).year
df['year']

In [ ]:
df

In [ ]:
diff = pd.date_range(start='1/1/2016', end='1/1/2020')
diff

In [ ]:
df['Month_Year'] = df['first_release_date'].dt.to_period('M')
df

In [ ]:
DF2 = df[(df['Month_Year'] >= '2016-01') & (df['Month_Year'] =< '2020-01')]
DF2

In [ ]:
DF2.groupby(['year', 'month']).count().sort_values('id', ascending = False)

In [ ]:
DF2.groupby(['year', 'month']).count().sort_values('id', ascending = False).plot.bar(rot = 45, figsize=(15,5))
None

In [27]:
df["weighted_score"] = df["rating"] * df["rating_count"]
df["weighted_score"]

C:\Users\klaud\AppData\Local\Temp\ipykernel_33732\1366953013.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["weighted_score"] = df["rating"] * df["rating_count"]

0           140.000000
41         2731.845011
124        1352.905401
326         825.992195
386       18227.183554
              ...
134889    36702.689204
134893    14187.278052
134898      505.765995
134899     1359.084845
134926      390.476190
Name: weighted_score, Length: 7960, dtype: float64

In [28]:
df

,id,name,platforms,first_release_date,category,genres,themes,player_perspectives,rating,rating_count,similar_games,total_rating,total_rating_count,url,aggregated_rating,aggregated_rating_count,weighted_score
0,70.0,"""TerraNova:StrikeForceCentauri""",13,1996-03-05,0.0,"5,13,15","1,18",1,70.000000,2.0,"13200,16806,17130,24620,25311,34823,55038,6828...",81.000000,3.0,"""https://www.igdb.com/games/terra-nova-strike-...",92.000000,1.0,140.000000
41,14543.0,"""BioShock2:Minerva'sDen""","6,9,12",2010-08-31,1.0,"5,31","1,18",1,85.370157,32.0,"55038,103276,103281,103292,103301,103329,10504...",83.185078,33.0,"""https://www.igdb.com/games/bioshock-2-minerva...",81.000000,1.0,2731.845011
124,76770.0,"""BridgeConstructorPortal""","3,6,14,34,39,48,49,130",2017-12-20,0.0,"9,13,15",18,4,71.205547,19.0,"8773,11666,13200,17130,24620,25311,34823,36258...",75.727774,23.0,"""https://www.igdb.com/games/bridge-constructor...",80.250000,4.0,1352.905401
326,9637.0,"""OrcsMustDie!Unchained""","6,45,48",2017-03-19,0.0,"11,15,24,32","1,17",2,75.090200,11.0,"2365,3222,5652,7027,9789,9834,9938,14394,19404",78.795100,13.0,"""https://www.igdb.com/games/orcs-must-die-unch...",82.500000,2.0,825.992195
386,2129.0,"""MarkoftheNinja""","3,6,12,14",2012-09-07,0.0,"8,31,32","1,23",4,84.777598,215.0,"3222,7213,11646,18182,19150,26226,26855,55190,...",88.103085,222.0,"""https://www.igdb.com/games/mark-of-the-ninja""",91.428571,7.0,18227.183554
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134889,80.0,"""TheWitcher""","6,14",2007-10-26,0.0,12,"1,17","2,3",83.037758,442.0,"6,76,472,478,660,1887,1942,3025,9938",85.518879,446.0,"""https://www.igdb.com/games/the-witcher""",88.000000,4.0,36702.689204
134893,521.0,"""Fable""",11,2004-09-14,0.0,"12,31","1,17,22,33",2,86.507793,164.0,"6,80,472,533,694,832,1026,1029,9927",88.253896,167.0,"""https://www.igdb.com/games/fable""",90.000000,3.0,14187.278052
134898,17583.0,"""SpellForce3""",6,2017-12-07,0.0,"11,12,15","1,17",3,38.905077,13.0,"19404,22387,23733,27092,28168,36198,54775,5509...",56.452538,24.0,"""https://www.igdb.com/games/spellforce-3""",74.000000,11.0,505.765995
134899,12527.0,"""Yakuza6:TheSongofLife""",48,2016-12-08,0.0,"14,25,31","1,38",2,84.942803,16.0,"10776,11397,12595,12736,25300,26574,28309,3024...",83.794931,35.0,"""https://www.igdb.com/games/yakuza-6-the-song-...",82.647059,19.0,1359.084845
134926,25741.0,"""AshesoftheSingularity:Escalation""",6,2016-11-10,4.0,"11,12,13,15,32","18,39",3,78.095238,5.0,"8773,9789,11666,13200,17130,25311,55029,78550,...",81.797619,7.0,"""https://www.igdb.com/games/ashes-of-the-singu...",85.500000,2.0,390.476190

In [32]:
df["normalized_weighted_score"] = (df["weighted_score"] - df["weighted_score"].min()) / (df["weighted_score"].max() - df["weighted_score"].min()) * 100

C:\Users\klaud\AppData\Local\Temp\ipykernel_33732\2852256536.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["normalized_weighted_score"] = (df["weighted_score"] - df["weighted_score"].min()) / (df["weighted_score"].max() - df["weighted_score"].min()) * 100

In [33]:
df["normalized_weighted_score"]

0          0.055276
41         1.078619
124        0.534170
326        0.326128
386        7.196669
            ...
134889    14.491384
134893     5.601587
134898     0.199692
134899     0.536610
134926     0.154172
Name: normalized_weighted_score, Length: 7960, dtype: float64

In [34]:
df["weighted_score"]

0           140.000000
41         2731.845011
124        1352.905401
326         825.992195
386       18227.183554
              ...
134889    36702.689204
134893    14187.278052
134898      505.765995
134899     1359.084845
134926      390.476190
Name: weighted_score, Length: 7960, dtype: float64

In [35]:
df["weighted_score"].min()

0.0

In [36]:
df["weighted_score"].max()

253272.49045030464

In [ ]:
#x κανονικοποιημένο = ( x - x ελάχιστο ) / ( x μέγιστο - x ελάχιστο )
#Τι είναι ο τύπος κανονικοποίησης;
#Στα στατιστικά στοιχεία, ο όρος «ομαλοποίηση» αναφέρεται στην κλιμάκωση του συνόλου δεδομένων έτσι ώστε τα κανονικοποιημένα δεδομένα να κυμαίνονται μεταξύ 0 και 1.